apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heart-disease-api
  namespace: bits-mlops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: heart-disease.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heart-disease-api
                port:
                  number: 80
