apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: heart-disease-api
  namespace: bits-mlops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: heart-disease-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
